engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: ".eslintrc.json"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "app/scripts/**"
  - "app/styles/**"
exclude_paths:
- "dist/**"
